### ISSUE TITLE
No Seal for MoC&E

### ISSUE THREAD

**Issue by TNP-Bug-Reporter** [The-North-Pacific/s13_TNP#18]
http://forum.thenorthpacific.org/pages/bug-report

1. Check all images. There is no seal for the MoC&amp;E.

As requested Eluvatar, here is the bug report you asked for. Apologies for the extensive delay.

For any other administrators that are wondering about this, Eluvatar requested I send a bug report for the seal.

~[Alvino Castillon](http://forum.thenorthpacific.org/profile/3142321)

**Comment by Eluvatar** [comment]
It was made:

http://www.thenorthpacific.org/images/moce-seal.png
