### ISSUE TITLE
Theme Changes and Threads

### ISSUE THREAD

**Issue by TNP-Bug-Reporter** [The-North-Pacific/s13_TNP#25]
http://forum.thenorthpacific.org/

1) Open a thread (specifically I was viewing this thread: http://forum.thenorthpacific.org/topic/7236078/ but it works on any thread)
2) Change forum theme (specifically I was changing from standard blue TNP to the Game of Thrones theme but it works between any themes)

Redirect/reload does not work. Attempted URL is &quot;http://forum.thenorthpacific.org/topic/7236078%2F1%2F&quot; with percent-two-eff instead of slashes. Error message is

&quot;Not Found

The requested URL /topic/7236078/1/ was not found on this server.&quot;

~[SillyString](http://forum.thenorthpacific.org/profile/3163742)

**Comment by Eluvatar** [comment]
I have also experienced this problem. My latest change makes the redirect send you back to "http://forum.thenorthpacific.org/" instead. I was unable to get the redirect back to whatever page you were on: replacing the %2Fs with /s somehow resulted in... a redirect back to the home page.

What's worse, this bug shows up on the main forum, but not on the test forum. Probably a zetaboards issue, will file a ticket.

**Comment by Eluvatar** [comment]
Finding http://support.zathyus.com/topic/5227287/1/ I see some solutions.
