### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by TNP-Bug-Reporter** [The-North-Pacific/s13_TNP#30]
http://forum.thenorthpacific.org/index/

Dunno

I am in this forum and i can't post what is this.

ps repair this pls or I will change region.

reps if it is not possible to repair doesn't matter.
but if it is possible and you don't repair it bye.

~[Aremanie](http://forum.thenorthpacific.org/profile/3262488)

**Comment by Eluvatar** [comment]
The user is in Validating and needs to post 3 times in the welcome areas or apply for Residence or Citizenship to gain the ability to post outside the welcome areas.

This is not a bug.
