### ISSUE TITLE
Strange forum

### ISSUE THREAD

**Issue by TNP-Bug-Reporter** [The-North-Pacific/s13_TNP#32]
http://forum.thenorthpacific.org/forum/39608/

Occurs whenever the Delegate's Government forum is viewed.

In the Delegate's Government forum, I'm seeing an empty forum with no folder icon, no name (and thus no link), no description, and an empty list of subforums listed between the Education and Forum News Box forums. It has a long list of moderators: &quot;Moderated By: embolalia, Abbey Anumia, Scandigrad, Mahaj, Romanoffia, Tim, Belschaft, punk d, Blue Wolf II, Kiwi, Kingborough, Alvino Castillon, Windsor, DRUK, Jamie, Sanctaria, Mall, Crushing Our Enemies, Cameron, Borndisaster, SillyString, Lennart, Ash, Abacathea, PaulWallLibertarian42, Lord Nwahs, Darcania, Cormac, Judicial Counsel&quot;. If it makes a difference, I have Resident masking.

Upon viewing the HTML source, the empty forum links to &quot;http://forum.thenorthpacific.org/forum//&quot;. The id for the table row the strange forum appears in is &quot;forum-&quot;. Which makes it appear that this ghost forum also has no id, either.

~[Darcania](http://forum.thenorthpacific.org/profile/3268033)

**Comment by Eluvatar** [comment]
Known Zetaboards bug.
