### ISSUE TITLE
Avatar Uploader

### ISSUE THREAD

**Issue by TNP-Bug-Reporter** [The-North-Pacific/s13_TNP#38]
http://forum.thenorthpacific.org/index/

Upload an image.

Every image file I upload results in the the same wrong image being processed. This problem has occurred on Chrome and Edge with the same problem persisting.

~[Zazumo](http://forum.thenorthpacific.org/profile/3279351)

**Comment by Eluvatar** [comment]
Doesn't appear to be an issue post-xenForo move
